## Exercise 0

In [5]:
def github() -> str:
    
    return "https://github.com/jphopk/ECON481-Homework/blob/main/ECON481-HW3-JustinHopkins.py"

## Exercise 1

In [6]:
import numpy as np
import pandas as pd

def import_yearly_data(years: list) -> pd.DataFrame:
    url_mapping = {
        2022: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2022.xlsx',
        2021: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2021.xlsx',
        2020: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2020.xlsx',
        2019: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2019.xlsx'
    }

    df = pd.DataFrame()
    for year in years:
        url = url_mapping.get(year)
        newDf = pd.read_excel(url, sheet_name = 'Direct Emitters', skiprows = 3)
        newDf.insert(0, 'year', year)
        df = pd.concat([df, newDf])
    
    return df

a = import_yearly_data([2022])
a

,year,Facility Id,FRS Id,Facility Name,City,State,Zip Code,Address,County,Latitude,...,Titanium Dioxide Production,Underground Coal Mines,Zinc Production,Municipal Landfills,Industrial Wastewater Treatment,Manufacture of Electric Transmission and Distribution Equipment,Industrial Waste Landfills,Is some CO2 collected on-site and used to manufacture other products and therefore not emitted from the affected manufacturing process unit(s)? (as reported under Subpart G or S),"Is some CO2 reported as emissions from the affected manufacturing process unit(s) under Subpart AA, G or P collected and transferred off-site or injected (as reported under Subpart PP)?",Does the facility employ continuous emissions monitoring?
0,2022,1002685,1.100712e+11,AC 857 A,Offshore,TX,0,NaN,NaN,26.295556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N
1,2022,1004377,1.100438e+11,121 REGIONAL DISPOSAL FACILITY,MELISSA,TX,75454,3820 SAM RAYBURN HIGHWAY,COLLIN COUNTY,33.298570,...,NaN,NaN,NaN,325416.25,NaN,NaN,NaN,N,N,N
2,2022,1010040,1.100712e+11,15-18565/15-18662,Hazard,KY,40701,1021 Tori Drive,PERRY COUNTY,37.274127,...,NaN,51538.75,NaN,NaN,NaN,NaN,NaN,N,N,N
3,2022,1000112,1.100712e+11,23rd and 3rd,BROOKLYN,NY,11232,730 3rd Avenue,Kings,40.663000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N
4,2022,1003742,1.100385e+11,31st Street Landfill,WESTCHESTER,IL,60154,11700 W 31ST ST,COOK COUNTY,41.834962,...,NaN,NaN,NaN,105999.75,NaN,NaN,NaN,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6486,2022,1011526,1.100213e+11,"Wild Goose Storage, LLC",Gridley,CA,95948,2780 West Liberty Rd.,BUTTE COUNTY,39.347640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N
6487,2022,1000912,1.100004e+11,Williams,GOOSE CREEK,SC,29445,2242 BUSHY PARK ROAD,Berkeley,33.016300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y
6488,2022,1001640,1.100712e+11,Wrenshall LNG Storage,Wrenshall,MN,55797,2301 County Road 1,CARLTON COUNTY,46.605400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N
6489,2022,1003436,1.100712e+11,Westdale Compressor Station,Coushatta,LA,71115,NaN,RED RIVER PARISH,32.198550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N
6490,2022,1008479,1.100419e+11,Willow Run Compressor Station,Ypsilanti,MI,48198,3020 East Michigan Ave.,WASHTENAW COUNTY,42.252800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N

## Exercise 2

In [7]:
import pandas as pd

def import_parent_companies(years: list) -> pd.DataFrame:
    parentSite = 'https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb'
    parentDf = pd.DataFrame()
    for year in years:
        newParentDf = pd.read_excel(parentSite, sheet_name = str(year))
        for index, row in newParentDf.iterrows():
            is_null_row = row.isnull().all()
            if is_null_row:
                newParentDf = newParentDf.drop(index)
        newParentDf.insert(0, 'year', year)
        parentDf = pd.concat([parentDf, newParentDf])
    return parentDf

b = import_parent_companies([2022])
b

,year,GHGRP FACILITY ID,FRS ID (FACILITY),REPORTING YEAR,FACILITY NAME,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,FACILITY COUNTY,PARENT COMPANY NAME,PARENT CO. STREET ADDRESS,PARENT CO. CITY,PARENT CO. STATE,PARENT CO. ZIP,PARENT CO. PERCENT OWNERSHIP,FACILITY NAICS CODE
0,2022,1000001,1.100005e+11,2022,PSE Ferndale Generating Station,5105 LAKE TERRELL ROAD,FERNDALE,WA,98248,WHATCOM COUNTY,PUGET HOLDINGS LLC,Po Box 97034,Bellevue,WA,98009,100.0,221112.0
1,2022,1000002,1.100412e+11,2022,Ardagh Glass Inc. (Dunkirk),524 E. CENTER STREET,DUNKIRK,IN,47336,JAY COUNTY,ARDAGH GLASS INC,"10194 Crosspoint Blvd, Suite 410",Indianapolis,IN,46256,100.0,327213.0
2,2022,1000003,1.100015e+11,2022,Ardagh Glass Inc. (Henderson),620 Facet Road,Henderson,NC,27537,VANCE COUNTY,ARDAGH GLASS INC,"10194 Crosspoint Blvd, Suite 410",Indianapolis,IN,46256,100.0,327213.0
3,2022,1000005,1.100005e+11,2022,Ardagh Glass Inc. (Madera),24441 AVENUE 12 & ROAD 24 1/2,MADERA,CA,93637,MADERA COUNTY,ARDAGH GLASS INC,"10194 Crosspoint Blvd, Suite 410",Indianapolis,IN,46256,100.0,327213.0
4,2022,1000007,1.100070e+11,2022,AMERICAN GYPSUM - BERNALILLO (WALLBOARD) PLANT,1000 N HILL RD,BERNALILLO,NM,87004,SANDOVAL COUNTY,EAGLE MATERIALS INC,"5960 Berkshire Lane, Suite 900",Dallas,TX,75225,100.0,327420.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8997,2022,1014728,1.100714e+11,2022,Vidor (ETC) Compressor Station,NaN,Vidor,TX,77662,ORANGE COUNTY,ENERGY TRANSFER LP,8111 Westchester Dr. Suite 600,Dallas,TX,75225,100.0,486210.0
8998,2022,1014729,1.100708e+11,2022,Tiger Plant,31783 US HWY 285,Orla,TX,79770,CULBERSON COUNTY,ENLINK MIDSTREAM LLC,1722 Routh Street Suite 1300,Dallas,TX,75201,100.0,211130.0
8999,2022,1014730,NaN,2022,Ameredev II 430 Permian Basin,2901 Via Fortuna Ste 600,Austin,TX,78746,NaN,Ameredev II LLC,2901 Via Fortuna # 600,Austin,TX,78746,100.0,211120.0
9000,2022,1014733,NaN,2022,"Oldach Associates, LLC","Road 869, corner of D street, Las Palmas Indus...",Catano,PR,962,NaN,Oldach Associates LLC,"Road 869, corner of D St. Las Palmas Industria...",Catano,PR,00962,100.0,424690.0
9001,2022,1014737,NaN,2022,"Sanguine Gas Exploration, LLC 345 Arkoma Basin...","110 West 7th Street, Suite 2700",Tulsa,OK,74119,NaN,SANGUINE GAS EXPLORATION LLC,"110 W 7TH ST, STE 2700",Tulsa,OK,74119,100.0,211130.0

## Exercise 3

In [8]:
def n_null(df: pd.DataFrame, col: str) -> int:
    null_count = df[col].isnull().sum()
    return null_count

df1 = import_yearly_data(([2022]))
n_null(df1, 'FRS Id')

166

## Exercise 4

In [9]:
def clean_data(emissions_data: pd.DataFrame, parent_data: pd.DataFrame) -> pd.DataFrame:
    url_mapping = {
        2022: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2022.xlsx',
        2021: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2021.xlsx',
        2020: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2020.xlsx',
        2019: 'https://lukashager.netlify.app/econ-481/data/ghgp_data_2019.xlsx'
    }
    parentSite = 'https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb'
    cleanDf = pd.DataFrame()
    cleanDf = pd.merge(emissions_data, parent_data, left_on=['year', 'Facility Id'], right_on=['year', 'GHGRP FACILITY ID'], how = 'left')
    

    cleaner_df = cleanDf[['Facility Id', 'year', 'State', 'Industry Type (sectors)', 
                            'Total reported direct emissions', 'PARENT CO. STATE', 
                            'PARENT CO. PERCENT OWNERSHIP']]
    
    cleaner_df.columns = cleaner_df.columns.str.lower()

    return cleaner_df

c = clean_data(a, b)
c

,facility id,year,state,industry type (sectors),total reported direct emissions,parent co. state,parent co. percent ownership
0,1002685,2022,TX,Petroleum and Natural Gas Systems,205454.158,TX,100.0
1,1004377,2022,TX,Waste,325416.250,TX,100.0
2,1010040,2022,KY,Other,51538.750,KY,100.0
3,1000112,2022,NY,Power Plants,68839.396,NY,100.0
4,1003742,2022,IL,Waste,106294.198,IL,100.0
...,...,...,...,...,...,...,...
7189,1011526,2022,CA,Petroleum and Natural Gas Systems,30334.040,DE,100.0
7190,1000912,2022,SC,"Petroleum and Natural Gas Systems,Power Plants",1702768.164,VA,100.0
7191,1001640,2022,MN,Petroleum and Natural Gas Systems,12101.354,NE,100.0
7192,1003436,2022,LA,Petroleum and Natural Gas Systems,21299.334,TX,100.0
7193,1008479,2022,MI,Petroleum and Natural Gas Systems,25603.958,MI,100.0

## Exercise 5

In [10]:
def aggregate_emissions(df: pd.DataFrame, group_vars: list) -> pd.DataFrame:
    aggVars = ['total reported direct emissions', 'parent co. percent ownership']
    aggDf = df.groupby(group_vars)[aggVars].agg(['min', 'median', 'mean', 'max'])
    aggDf = aggDf.sort_values(by=('total reported direct emissions', 'mean'), ascending=False)
    
    return aggDf
d = aggregate_emissions(c, ['state'])
d
#duplicates = d[d.duplicated()]
#duplicates

      total reported direct emissions                                          \
                                  min      median          mean           max
state
MT                            882.448  195997.031  2.097366e+06  1.074066e+07
WY                           3007.644  160314.056  1.473675e+06  1.152466e+07
AR                             69.500   79829.368  1.093898e+06  5.709994e+06
IA                              0.000  103111.708  9.240167e+05  6.601780e+06
UT                            179.598   83197.117  8.625275e+05  7.518232e+06
MO                           1142.396   70174.986  7.817144e+05  1.586076e+07
NM                              0.000   58331.852  7.727947e+05  9.813100e+06
IN                            151.000   75097.355  7.134000e+05  1.041436e+07
CO                              0.000   71031.080  6.908444e+05  7.958392e+06
AZ                            132.548   63724.906  6.424013e+05  7.497856e+06
PR                              0.000   97634.183  6.158660e+05  3.474944e+06
FL                           2044.792  110041.930  6.091368e+05  8.780184e+06
ND                             33.300   98896.887  6.003857e+05  8.785254e+06
WV                              0.000   80223.305  6.002707e+05  1.169416e+07
GA                           7914.500   73680.520  5.478954e+05  8.475024e+06
KY                              1.096   68848.043  5.442860e+05  9.887785e+06
PA                            218.124   62665.624  5.109597e+05  5.446609e+06
WI                             37.600   60146.574  5.057686e+05  5.324629e+06
AL                           3656.936  190399.143  4.863194e+05  2.177544e+07
DE                           8162.750   51092.077  4.691283e+05  3.680307e+06
TX                              0.000   88156.286  4.612128e+05  1.333042e+07
NV                           7220.750  198671.259  4.518891e+05  2.202264e+06
OH                            903.836   71817.820  4.471864e+05  1.129861e+07
MS                            702.496   63253.152  4.347680e+05  6.018792e+06
AK                            161.700  161270.256  4.290754e+05  2.996872e+06
MI                             43.200   57739.525  4.146078e+05  1.490813e+07
NC                            192.100   68847.020  4.033848e+05  5.922637e+06
MD                           6226.250  100083.401  3.950259e+05  2.219520e+06
NJ                            188.700   54188.722  3.914640e+05  2.709778e+06
MN                             11.100   74196.306  3.913464e+05  1.046929e+07
CT                           6159.000   90396.425  3.873800e+05  2.189121e+06
NE                           6483.628   73301.484  3.767339e+05  7.110140e+06
IL                              0.000   50719.934  3.741207e+05  1.102577e+07
LA                              0.000   76015.648  3.683229e+05  9.155496e+06
SC                            343.648   67525.016  3.641800e+05  7.687274e+06
TN                          11881.020   70972.284  3.157620e+05  7.694050e+06
KS                           1254.096   53904.640  3.155067e+05  9.449839e+06
RI                           4688.098  211125.287  3.032445e+05  1.246513e+06
VA                              0.000   70170.750  2.929643e+05  3.897339e+06
OK                              0.000   57401.936  2.917723e+05  3.753893e+06
SD                             91.300   69772.088  2.564125e+05  2.188991e+06
OR                            701.132   60965.500  2.494622e+05  1.530100e+06
HI                              0.000   59330.640  2.405793e+05  2.018125e+06
WA                              0.000   67074.951  2.381858e+05  3.953535e+06
CA                              0.000   47709.872  2.358807e+05  6.263565e+06
NY                              0.000   58003.982  1.833032e+05  2.912919e+06
NH                           1044.482   52002.450  1.709193e+05  1.326883e+06
VI                            235.000   83518.800  1.457700e+05  3.422856e+05
GU                           6505.494   86779.346  1.453576e+05  5.099406e+05
MA                            994.500   48644.010  1.451275e+05  1.411784e+06
ID                           5159.580   75225.544  1.364520e+05  6.389234e+05
ME                           6817.000   30604.396  1.117960e+05  9.208089e+05
VT                          29011.738   36047.154  8.343109e+04  2.529765e+05
DC                          15535.544   35441.315  4.856791e+04  1.105551e+05

      parent co. percent ownership
                               min  median        mean    max
state
MT                          5.1100  100.00   82.352941  100.0
WY                          1.3700  100.00   83.540127  100.0
AR                          0.5000  100.00   82.608696  100.0
IA                          0.0700  100.00   79.057644  100.0
UT                          2.0800  100.00   92.753623  100.0
MO                          2.0000  100.00   93.636364  100.0
NM                          0.7000  100.00   80.188585  100.0
IN                          4.9400  100.00   94.871795  100.0
CO                          4.1900  100.00   86.259542  100.0
AZ                          8.0000  100.00   90.816327  100.0
PR                        100.0000  100.00  100.000000  100.0
FL                          1.0000  100.00   93.121693  100.0
ND                          0.6600  100.00   84.210526  100.0
WV                         35.0000  100.00   96.491228  100.0
GA                          0.0000  100.00   92.696573  100.0
KY                         40.0000  100.00   99.224806  100.0
PA                          0.0000  100.00   94.684352  100.0
WI                          0.8000  100.00   94.160584  100.0
AL                          0.0000  100.00   70.212596  100.0
DE                          0.0000  100.00   90.909091  100.0
TX                          0.0000  100.00   88.702601  100.0
NV                         38.5000  100.00   88.636364  100.0
OH                         18.7000  100.00   93.866171  100.0
MS                          0.1000  100.00   90.480342  100.0
AK                          0.0200   92.52   63.743956  100.0
MI                          1.0000  100.00   95.495495  100.0
NC                          8.0000  100.00   96.850394  100.0
MD                         25.0000  100.00   93.750000  100.0
NJ                          8.0774  100.00   90.322581  100.0
MN                          1.0000  100.00   94.814815  100.0
CT                         10.7900  100.00   90.243659  100.0
NE                          3.0000  100.00   94.871795  100.0
IL                          1.0000  100.00   95.258621  100.0
LA                          0.1000  100.00   84.119897  100.0
SC                         13.0000  100.00   96.842105  100.0
TN                         30.0000  100.00   98.148148  100.0
KS                          0.7551  100.00   91.379303  100.0
RI                        100.0000  100.00  100.000000  100.0
VA                         10.0000  100.00   96.875000  100.0
OK                          6.2500  100.00   90.607735  100.0
SD                         22.7000  100.00   95.121951  100.0
OR                         50.0000  100.00   96.491228  100.0
HI                         30.0000  100.00   96.551724  100.0
WA                         33.3300  100.00   95.789368  100.0
CA                          0.0000  100.00   89.135778  100.0
NY                          0.0000  100.00   94.811321  100.0
NH                        100.0000  100.00  100.000000  100.0
VI                        100.0000  100.00  100.000000  100.0
GU                        100.0000  100.00  100.000000  100.0
MA                          0.4400  100.00   94.202899  100.0
ID                         50.0000  100.00   97.368421  100.0
ME                          0.0800  100.00   80.000000  100.0
VT                        100.0000  100.00  100.000000  100.0
DC                        100.0000  100.00  100.000000  100.0